# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - azure-pipelines.yml
    
variables:
  buildConfiguration: 'Release'
  vmImageName: 'windows-latest'

stages:
- stage: Build
  displayName: Build Stage

  jobs:
  - job: Build
    displayName: Build

    pool:
      vmImage: $(vmImageName)

    steps:
    - task: DotNetCoreCLI@2
      displayName: Build Server
      inputs:
        command: 'build'
        projects: '**/EmptyApp.csproj'

- stage: Release
  displayName: Release stage

  jobs:
  - job: Release
    displayName: Release to Azure

    pool:
      vmImage: $(vImageName)

    steps:
    - task: DotNetCoreCLI@2
      displayName: Publish to project
      inputs:
        command: 'publish'
        publishWebProjects: true

    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: '62eeb809-9772-486e-92e9-a549e6ba9347'
        WebAppName: 'EmptyApp-Blazor-Test'
        package: '$(System.DefaultWorkingDirectory)/**/*.zip'
  